<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Purchase Report</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #222; }
        h1 { text-align: center; margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #555; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; }
        .summary { margin-top: 20px; text-align: right; font-weight: bold; }
    </style>
</head>
<body>
    <h1>Purchase Report</h1>
    <p><strong>Generated On:</strong> {{ now()->format('d M, Y h:i A') }}</p>
    <p><strong>Generated By:</strong> {{ Auth::user()->name }}</p>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Product</th>
                <th>Supplier</th>
                <th>Quantity</th>
                <th>Price (Rs.)</th>
                <th>Total (Rs.)</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($purchases as $index => $purchase)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $purchase->name }}</td>
                    <td>{{ $purchase->supplier->name }}</td>
                    <td>{{ $purchase->quantity }}</td>
                    <td>{{ number_format($purchase->purchase_price, 2) }}</td>
                    <td>{{ number_format($purchase->quantity * $purchase->purchase_price, 2) }}</td>
                    <td>{{ \Carbon\Carbon::parse($purchase->purchase_date)->format('d M, Y') }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

</body>
</html>
